# Generated by Django 5.1.3 on 2025-01-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='score2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
